name: 'Run woke'
description: 'Run woke on pull requests to detect non-inclusive language in your source code.'
author: 'Caitlin Elfring (caitlinelfring)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for woke ###
  woke_args:
    description: 'woke arguments'
    default: '.'
    required: false
  woke_version:
    description: 'woke version'
    default: '' # uses latest, should be pinned? # 'v0.1'
    required: false
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.com/actions/runner/issues/665
        INPUT_WOKE_VERSION: ${{ inputs.woke_version }}
        INPUT_WOKE_FLAGS: ${{ inputs.woke_args }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check-circle'
  color: 'gray-dark'
